# Marketplace commission and fee structure

commission:
  # Fixed commission for items under threshold
  fixed:
    amount: 15.0
    threshold: 150.0
    currency: "USD"
  
  # Percentage commission for items above threshold
  percentage:
    rate: 0.10  # 10%
    minimum: 0.0
    currency: "USD"

# Shopfans shipping calculation with tiered pricing
shopfans:
  base_cost: 13.99
  # Tiered per-kg rates based on total order value (item + US shipping)
  per_kg_rates:
    europe: 30.86    # < $200 - via Europe
    turkey: 35.27    # >= $200 - via Turkey  
    kazakhstan: 41.89 # >= $1000 - via Kazakhstan
  # Rate thresholds based on item + US shipping cost
  rate_thresholds:
    turkey: 200.0    # >= $200 uses Turkey route
    kazakhstan: 1000.0 # >= $1000 uses Kazakhstan route
  handling_fee:
    light_items: 3.0  # for items <= 1.36kg (3 pounds)
    heavy_items: 5.0  # for items > 1.36kg (3 pounds)
  light_threshold: 1.36  # 3 pounds = 1.36 kg

# Currency exchange
currency:
  markup_percentage: 5.0  # 5% markup on official rates
  default_source: "cbr"
  fallback_enabled: false

# Default shipping costs
shipping:
  default_us: 15.0  # Default US shipping for Grailed if not found
  free_keywords: ["free", "бесплатно"]